name: pspnet_kerastf
channels:
  - defaults
  - anaconda
dependencies:
  - python=3.5
  - pip
  - pip:
    - scipy==1.2.2
    - numpy==1.14.6
    - pytest-xdist==1.29.0
    - imageio==2.5.0
    - pytest==5.1.3
    - keras==2.1.1
    - opencv-python==4.1.1.26
    - tensorflow==1.0.0
    - matplotlib
    - h5py
    - tensorflow-gpu

